version: '3.8'

services:
  app:
    build: .
    ports:
      - "5173:5173"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tarea3
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_SQL_INIT_MODE=always
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_JDBC_DATASOURCE_INIT=DEBUG
    restart: always
    networks:
      - spring-network

  postgres:
    image: postgres:15
    container_name: postgres-tarea3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tarea3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - spring-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  postgres-data:
    name: postgres-data-tarea3-new

networks:
  spring-network:
    driver: bridge